services:
  terraria:
    container_name: 'terraria'
    build: .
    image: terraria:local
    restart: unless-stopped
    healthcheck:
      test: "nc -z 127.0.0.1 6000 || exit 1"
      interval: 30s
      timeout: 5s
      start_period: 10s
      retries: 3
      x-podman.on_failure: restart
    ports:
      - '127.0.0.1:7778:7777'
    expose:
      - '6000'
    volumes:
      - /srv/terraria:/data:z
      - ./control/api:/www/cgi-bin/api
    env_file:
      - .env
    entrypoint: [ "/bin/sh", "-c", "./entrypoint.sh & exec busybox httpd -f -p 6000 -h /www" ]

  web:
    container_name: 'web'
    build: ./control/frontend
    image: terraria/web-server:local
    restart: unless-stopped
    healthcheck:
      test: "wget --quiet --tries=1 --spider http://127.0.0.1:8080 || exit 1"
      interval: 30s
      timeout: 5s
      start_period: 10s
      retries: 3
    ports:
      - 6001:8080
    env_file:
      - ./control/redis/redis.env

  api:
    container_name: 'api'
    build:
      args:
        - NODE_ENV=production
      context: ./control/backend
      target: production
    command: npm run start-watch
    image: node:alpine
    ports:
      - '8000:8000'
    env_file:
      - ./control/redis/redis.env
    environment:
      JWT_SECRET: ${JWT_SECRET}
      ALLOWED_ORIGINS: http://web:5173
    secrets:
      - users
    volumes:
      - ./control/backend/src:/code/src:ro
      - ./control/backend/package.json:/code/package.json
      - ./control/backend/package-lock.json:/code/package-lock.json
    depends_on:
      - terraria

  redis:
    image: redis:alpine
    restart: always
    healthcheck:
      test: [ "CMD", "/usr/local/bin/healthcheck.sh" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    command: [ "redis-server", "/etc/redis/redis.conf" ]
    env_file:
      - ./control/redis/redis.env
    volumes:
      - ./control/redis/redis.conf:/etc/redis/redis.conf:Z,ro
      - ./control/redis/healthcheck.sh:/usr/local/bin/healthcheck.sh:Z,ro
      - redis_data:/data

volumes:
  redis_data:

secrets:
  users:
    file: ./users.json
