services:
  tmodloader:
    container_name: 'terraria'
    build: .
    image: terraria:local
    healthcheck:
      test: "nc -vz 127.0.0.1 7777 || exit 1"
      interval: 30s
      timeout: 5s
      start_period: 30s
      retries: 3
    ports:
      - '127.0.0.1:7778:7777'
    volumes:
      - /srv/terraria:/data:z
    env_file:
      - /opt/terraria/terraria.env
