services:
  terraria:
    container_name: 'terraria'
    build: ..
    image: terraria:local
    restart: unless-stopped
    healthcheck:
      test: "nc -z 127.0.0.1 6002 || exit 1"
      interval: 30s
      timeout: 5s
      start_period: 10s
      retries: 3
      x-podman.on_failure: restart
    ports:
      - '6002:6002'
    expose:
      - 6002
    volumes:
      - server_data:/data
      - ../control/api:/www/cgi-bin/api:Z,ro
    env_file:
      - .env
    entrypoint: [ "/bin/sh", "-c", "./entrypoint.sh & tail -F /tmp/busy.pipe & exec busybox httpd -f -p 6002 -h /www" ]

  web:
    container_name: 'web'
    build:
      context: ../control/frontend
      target: development
    image: terraria-web-server:local
    restart: unless-stopped
    healthcheck:
      test: "wget --quiet --tries=1 --spider http://127.0.0.1:5173 || exit 1"
      interval: 30s
      timeout: 5s
      start_period: 10s
      retries: 3
    environment:
      CHOKIDAR_USEPOLLING: true
      CHOKIDAR_INTERVAL: 100
    ports:
      - 5173:5173
    volumes:
      - ../control/frontend:/app:Z,ro
      - /app/node_modules
    env_file:
      - ../control/frontend/.env

  api:
    container_name: 'api'
    build:
      args:
        - NODE_ENV=development
      context: ../control/backend
      target: development
    ports:
      - '8000:8000'
    env_file:
      - ../control/redis/redis.env
    environment:
      NODE_ENV: development
      JWT_SECRET: ${JWT_SECRET}
      ALLOWED_ORIGINS: http://localhost:5173
      CHOKIDAR_USEPOLLING: true
      CHOKIDAR_INTERVAL: 100
    secrets:
      - users
    volumes:
      - ../control/backend/src:/code/src:Z,ro
      - ../control/backend/package.json:/code/package.json:Z,ro
      - ../control/backend/package-lock.json:/code/package-lock.json:Z,ro
      - /code/node_modules

  redis:
    image: redis:alpine
    restart: always
    healthcheck:
      test: [ "CMD", "/usr/local/bin/healthcheck.sh" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    command: [ "redis-server", "/etc/redis/redis.conf" ]
    env_file:
      - ../control/redis/redis.env
    volumes:
      - ../control/redis/redis.conf:/etc/redis/redis.conf:Z,ro
      - ../control/redis/healthcheck.sh:/usr/local/bin/healthcheck.sh:Z,ro
      - redis_data:/data

secrets:
  users:
    file: ../example.users.json

volumes:
  server_data:
  redis_data:
  node_modules:
