#!/bin/sh
pipe=/tmp/busy.pipe
pidfile=/tmp/terraria.pid

printf "Content-Type: text/plain\r\n\r\n"

if [ ! -f "$pidfile" ] || ! kill -0 "$(cat "$pidfile")" 2>/dev/null; then
    echo "Terraria server is not running" >> $pipe
    if [ "$PATH_INFO" != "/start" ]; then
        echo "STOPPED"
        exit 0
    fi
fi

case "$REQUEST_METHOD" in
    GET)
        case "$PATH_INFO" in
            /status)
                tmux send-keys "playing" Enter

                sleep 1

		status=$(
    			tmux capture-pane -p \
		        | tail -n 3 \
		        | awk '/connected/{print $1}'
		)

		case "$status" in
			:)
				echo "0"
				;;
    			*[!0-9]*|'')
				echo "CHANGING"
				;;
			*)
				echo "$status"
				;;
		esac
                ;;
            *)
                echo "Unknown GET endpoint"
                ;;
        esac
        ;;

    POST)
        case "$PATH_INFO" in
            /stop)
                echo "Received command to stop server" >> $pipe

                tmux send-keys "say $TMOD_SHUTDOWN_MESSAGE" Enter
                sleep 3
                tmux send-keys "exit" Enter
		sleep 5
                kill $(pgrep -f autosave.sh)
                echo "OK"
                ;;

            /start)
                echo "Received command to start server" >> $pipe

                cd /terraria-server

		if [ ! -f "$pidfile" ] || ! kill -0 "$(cat "$pidfile")" 2>/dev/null; then
			nohup ./entrypoint.sh >/dev/null 2>&1 &
	                echo "Initiated server start" >> $pipe
		fi

                echo "OK"
                ;;

            /midnight)
                echo "Received command to set time to midnight" >> $pipe
                tmux send-keys "say Setting time to midnight" Enter

                tmux send-keys "midnight" Enter
                echo "OK"
                ;;

            /dawn)
                echo "Received command to set time to dawn" >> $pipe
                tmux send-keys "say Setting time to dawn" Enter


                tmux send-keys "dawn" Enter
                echo "OK"
                ;;

            /noon)
                echo "Received command to set time to noon" >> $pipe
                tmux send-keys "say Setting time to noon" Enter

                tmux send-keys "noon" Enter
                echo "OK"
                ;;

            /dusk)
                echo "Received command to set time to dusk" >> $pipe
                tmux send-keys "say Setting time to dusk" Enter

                tmux send-keys "dusk" Enter
                echo "OK"
                ;;

            /save)
                echo "Received command to save world" >> $pipe

                tmux send-keys "save" Enter
                echo "OK"
                ;;

            *)
                echo "Received request on unknown endpoint" >> $pipe

                echo "Unknown POST endpoint"
                ;;
        esac
        ;;

    *)
         echo "Received request using a not supported method" >> $pipe

        echo "Method Not Allowed"
        ;;
esac
