name: "Build"

on:
  workflow_call:
    inputs:
      SHOULD_UPDATE:
        required: true
        type: string
        description: "Whether to update the tModLoader version"
      REPO_VERSION:
        required: false
        default: ""
        type: string
        description: "The latest tModLoader version"
      CURRENT_VERSION:
        required: false
        default: ""
        type: string
        description: "The currently used tModLoader version"

permissions:
  contents: read
  packages: write

jobs:
  build:
    name: Docker Images
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
      COMPOSE_DOCKER_CLI_BUILD: 1
      SHOULD_UPDATE: ${{ inputs.SHOULD_UPDATE }}
      REPO_VERSION: ${{ inputs.REPO_VERSION }}
      CURRENT_VERSION: ${{ inputs.CURRENT_VERSION }}

    strategy:
      matrix:
        image:
          - name: tmodloader1.4
            dockerfile: Dockerfile
            context: .
          - name: terraria-frontend
            dockerfile: control/frontend/Dockerfile
            context: .
            target: production
          - name: terraria-backend
            dockerfile: control/backend/Dockerfile
            context: .
            target: development
            args: NODE_ENV=development

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Update Dockerfile Version
        if: ${{ env.SHOULD_UPDATE == 'true' }}
        run: sed -i "s/${{ env.CURRENT_VERSION }}/${{ env.REPO_VERSION }}/" ./Dockerfile

      - name: Login to GHCR
        if: ${{ github.event_name != 'pull_request' || !github.event.pull_request.head.repo.fork }}
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - uses: docker/build-push-action@v7
        with:
          context: ${{ matrix.image.context }}
          file: ${{ matrix.image.dockerfile }}
          target: ${{ matrix.image.target }}
          tags: nonjerry/${{ matrix.image.name }}:ci
          load: true
          cache-from: |
            type=gha,scope=${{ matrix.image.name }}
            type=registry,ref=ghcr.io/nonjerry/${{ matrix.image.name }}:buildcache
          cache-to: |
            type=gha,mode=max,scope=${{ matrix.image.name }}
            ${{ github.event_name != 'pull_request' || !github.event.pull_request.head.repo.fork && format('type=registry,mode=max,ref=ghcr.io/nonjerry/{0}:buildcache', matrix.image.name) || '' }}

      - run: docker save nonjerry/${{ matrix.image.name }}:ci -o ${{ matrix.image.name }}-image.tar

      - uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.image.name }}-image
          path: ${{ matrix.image.name }}-image.tar

  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Install pnpm
        uses: pnpm/action-setup@v6

      - name: Install deps
        run: pnpm install

      - name: Lint repository
        run: pnpm lint

      - name: Build repository
        run: pnpm build
