name: Pull Request Validation

on:
  pull_request:
    branches:
      - master

permissions:
  contents: read
  packages: write

jobs:
  build:
    name: Build Docker Images
    uses: ./.github/workflows/build.yml
    with:
      SHOULD_UPDATE: false

  tests:
    name: Run Tests
    needs: build
    uses: ./.github/workflows/test.yml
    with:
      SHOULD_UPDATE: false
