name: "Test"

on:
  workflow_call:
    inputs:
      SHOULD_UPDATE:
        required: true
        type: string
        description: "Whether to update the tModLoader version"
      REPO_VERSION:
        required: true
        type: string
        description: "The latest tModLoader version"
      CURRENT_VERSION:
        required: true
        type: string
        description: "The currently used tModLoader version"

permissions:
  contents: write

jobs:
  unit:
    runs-on: ubuntu-latest
    env:
      PUPPETEER_SKIP_DOWNLOAD: "true"
      SHOULD_UPDATE: ${{ inputs.SHOULD_UPDATE }}
      REPO_VERSION: ${{ inputs.REPO_VERSION }}
      CURRENT_VERSION: ${{ inputs.CURRENT_VERSION }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Update Dockerfile Version
        if: ${{ env.SHOULD_UPDATE == 'true' }}
        run: sed -i "s/${{ env.CURRENT_VERSION }}/${{ env.REPO_VERSION }}/" ./Dockerfile

      - name: Install pnpm
        uses: pnpm/action-setup@v6

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          registry-url: "https://registry.npmjs.org"
          cache: "pnpm"

      - name: Install deps
        run: pnpm install

      - name: Run unit tests
        run: pnpm run test

  e2e:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
      COMPOSE_DOCKER_CLI_BUILD: 1
      SHOULD_UPDATE: ${{ inputs.SHOULD_UPDATE }}
      REPO_VERSION: ${{ inputs.REPO_VERSION }}
      CURRENT_VERSION: ${{ inputs.CURRENT_VERSION }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - uses: actions/download-artifact@v7
        with:
          name: terraria-backend-image
          path: ${{ runner.temp }}/
      - run: docker load -i ${{ runner.temp }}/terraria-backend-image.tar

      - uses: actions/download-artifact@v7
        with:
          name: terraria-frontend-image
          path: ${{ runner.temp }}/
      - run: docker load -i ${{ runner.temp }}/terraria-frontend-image.tar

      - uses: actions/download-artifact@v7
        with:
          name: tmodloader1.4-image
          path: ${{ runner.temp }}/
      - run: docker load -i ${{ runner.temp }}/tmodloader1.4-image.tar

      - name: Update Dockerfile Version
        if: ${{ env.SHOULD_UPDATE == 'true' }}
        run: sed -i "s/${{ env.CURRENT_VERSION }}/${{ env.REPO_VERSION }}/" ./Dockerfile

      - name: Setup cache for Playwright browsers
        uses: actions/cache@v5
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Install pnpm
        uses: pnpm/action-setup@v6

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          registry-url: "https://registry.npmjs.org"
          cache: "pnpm"

      - name: Install deps
        run: pnpm install

      - name: Install Browsers
        working-directory: control/frontend
        run: pnpm playwright install --with-deps

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Create empty config files
        run: touch .env dev/.env control/frontend/.env control/backend/.env control/redis/redis.env control/redis/redis.conf

      - name: Build and Start Docker Full Stack
        run: pnpm full-stack-no-build:docker

      - name: Run e2e tests
        run: pnpm test:e2e