name: tModLoader Stable Version Auto-Updater
on:
  schedule:
    - cron: "5 2 * * *"

permissions:
  contents: write
  packages: write

jobs:
  check-tmodloader-version:
    name: Check tModLoader Version
    runs-on: ubuntu-latest
    outputs:
      SHOULD_UPDATE: ${{ steps.compareVersions.outputs.SHOULD_UPDATE }}
      CURRENT_VERSION: ${{ steps.getCurrentVersion.outputs.CURRENT_VERSION }}
      REPO_VERSION: ${{ steps.getRepoVersion.outputs.REPO_VERSION }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7
        with:
          sparse-checkout: |
            Dockerfile

      - name: Get Current Version
        id: getCurrentVersion
        run: echo "CURRENT_VERSION=$(grep -oP '(?<=\bTMOD_VERSION=)[^;]+' ./Dockerfile)" >> $GITHUB_OUTPUT

      - name: Get Repository Version
        id: getRepoVersion
        run: echo "REPO_VERSION=$(curl -sL https://api.github.com/repos/tModLoader/tModLoader/releases | jq -r 'map(select(.prerelease==false)) | first | .tag_name')" >> $GITHUB_OUTPUT
        
      - name: Compare Versions
        id: compareVersions
        run: echo "SHOULD_UPDATE=${{ steps.getCurrentVersion.outputs.CURRENT_VERSION != steps.getRepoVersion.outputs.REPO_VERSION }}" >> $GITHUB_OUTPUT

  build:
    name: Build
    if: ${{ needs.check-tmodloader-version.outputs.SHOULD_UPDATE == 'true' }}
    needs: check-tmodloader-version
    uses: ./.github/workflows/build.yml
    with:
      SHOULD_UPDATE: ${{ needs.check-tmodloader-version.outputs.SHOULD_UPDATE }}
      REPO_VERSION: ${{needs.check-tmodloader-version.outputs.REPO_VERSION}}
      CURRENT_VERSION: ${{needs.check-tmodloader-version.outputs.CURRENT_VERSION}}

  tests:
    name: Tests
    needs:
      - check-tmodloader-version
      - build
    if: ${{ needs.check-tmodloader-version.outputs.SHOULD_UPDATE == 'true' }}
    uses: ./.github/workflows/test.yml
    with:
      SHOULD_UPDATE: ${{ needs.check-tmodloader-version.outputs.SHOULD_UPDATE }}
      REPO_VERSION: ${{needs.check-tmodloader-version.outputs.REPO_VERSION}}
      CURRENT_VERSION: ${{needs.check-tmodloader-version.outputs.CURRENT_VERSION}}

  update-dockerfile:
    name: Update Dockerfile in Docker Registry
    if: ${{ needs.check-tmodloader-version.outputs.SHOULD_UPDATE == 'true' }}
    needs:
      - check-tmodloader-version
      - tests
    uses: ./.github/workflows/update-tmodloader-image.yml
    secrets: inherit
    with:
      SHOULD_UPDATE: ${{ needs.check-tmodloader-version.outputs.SHOULD_UPDATE }}
      REPO_VERSION: ${{needs.check-tmodloader-version.outputs.REPO_VERSION}}
      CURRENT_VERSION: ${{needs.check-tmodloader-version.outputs.CURRENT_VERSION}}
