name: "Update Dockerfile in Docker Registry"

on:
  workflow_call:
    inputs:
      SHOULD_UPDATE:
        required: true
        type: string
        description: "Whether to update the tModLoader version"
      REPO_VERSION:
        required: true
        type: string
        description: "The latest tModLoader version"
      CURRENT_VERSION:
        required: true
        type: string
        description: "The currently used tModLoader version"

permissions:
  contents: write
  packages: write

jobs:
  update-tmodloader-image:
    name: Update Docker Image in Docker Registry
    runs-on: ubuntu-latest
    env:
      SHOULD_UPDATE: ${{ inputs.SHOULD_UPDATE }}
      REPO_VERSION: ${{ inputs.REPO_VERSION }}
      CURRENT_VERSION: ${{ inputs.CURRENT_VERSION }}
      DOCKER_BUILDKIT: 1
      COMPOSE_DOCKER_CLI_BUILD: 1
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7
        with:
          sparse-checkout: .

      - uses: actions/download-artifact@v7
        with:
          name: tmodloader1.4-image
          path: ${{ runner.temp }}/
      - run: docker load -i ${{ runner.temp }}/tmodloader1.4-image.tar
      - run: docker tag nonjerry/tmodloader1.4:ci nonjerry/tmodloader1.4:latest
      - run: docker tag nonjerry/tmodloader1.4:ci nonjerry/tmodloader1.4:${{ env.REPO_VERSION }}

      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      
      - name: Login to GHCR
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build and push Docker Image
        uses: docker/build-push-action@v7
        with:
          push: true
          load: true
          cache-from: |
            type=gha,scope=tmodloader1.4
            type=registry,ref=ghcr.io/nonjerry/tmodloader1.4:buildcache
          cache-to: |
            type=gha,mode=max,scope=tmodloader1.4
            type=registry,mode=max,ref=ghcr.io/nonjerry/tmodloader1.4:buildcache
          tags: |
            ${{ vars.DOCKER_USER }}/tmodloader1.4:${{ env.REPO_VERSION }}
            ${{ vars.DOCKER_USER }}/tmodloader1.4:latest

      - uses: stefanzweifel/git-auto-commit-action@v7
        if: ${{ env.SHOULD_UPDATE == 'true' }}
        with:
          commit_user_name: Merge Bot
          commit_message: "Github Action: Updating to tModLoader version ${{ env.REPO_VERSION }}"
          commit_options: "--no-verify --signoff"
          repository: .
          tagging_message: "${{ env.REPO_VERSION }}"
          skip_fetch: true
          skip_checkout: true
          create_branch: false
